### ISSUE TITLE
python-psycopg2 설치 문제 관련 문의

### ISSUE THREAD

**Issue by sungchan1025** [snoop2head/docker_konlpy_django#1]
안녕하세요! 다운 받아서 빌드해보는데 아래와 같은 에러가 나는데 혹시 해결책을 알고 계실까요??

좋은 코드 감사 드립니다!

Step 9/31 : RUN apt-get install -y python-psycopg2
 ---> Running in ce57a02de04b
Reading package lists...
Building dependency tree...
Reading state information...
Package python-psycopg2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by snoop2head** [comment]
안녕하세요.
일단 README.md가 정비가 안 되어 있는 점은 양해 부탁드립니다. 조만간 업데이트하겠습니다.
* 개발 환경을 간단하게 설명해주실 수 있을까요? 어떤 목적으로 사용하실 계획인가요?
* `docker image pull snoop2head/django_konlpy_postgres` 
    혹은 
   `docker image --no-cache build .` 를 시도해보시겠어요?

**Comment by sungchan1025** [comment]
안녕하세요!

개발환경은 python3.7에 django 3.0이었습니다. 알려주신 방법 포함 해봤는데 역시 환경 문제였습니다...

RUN apt-get install -y python-psycopg2

를 

RUN apt-get install -y python3-psycopg2

로 바꾸니 정상 동작하네요ㅠㅠ 사용목적은 사내 챗봇서버를 구축하는데 그냥 django를 깔아서 쓰다가 AWS ECS로 서비스를 옮기면서 도커라이징이 필요했습니다!

답변 너무 감사 드립니다!

**Comment by snoop2head** [comment]
아아 그렇네요 ㅎㅎ  [스택 오버 플로에도 유사한 경우를 찾았습니다.](https://stackoverflow.com/a/56283445/8380469)
반영해서 수정하도록 하겠습니다!
기여 감사합니다 😄
